### ISSUE TITLE
Fatal error after upgrade to 3.6.0-beta.1

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#136]
So I updated phab with `phab self-update --allow-unstable=ALLOW-UNSTABLE` and that reported

> [OK] Updated phabalicious successfully to 3.6.0-beta.1

after that running any phab command results in following PHP Fatal error:

```
09:32 $ phab
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phabalicious\Command\BackupBaseCommand" cannot have an empty name. in phar:///usr/local/bin/phab/vendor/symfony/console/Application.php:489
Stack trace:
#0 /tmp/phabalicious3.6.07ea8cfa7b86c2865d3b638d690c7a809/Container5nMqo29/getApplicationService.php(40): Symfony\Component\Console\Application->add()
#1 /tmp/phabalicious3.6.07ea8cfa7b86c2865d3b638d690c7a809/Container5nMqo29/srcPhabalicious_AppKernelProdContainer.php(63): require('/tmp/phabalicio...')
#2 phar:///usr/local/bin/phab/vendor/symfony/dependency-injection/Container.php(255): Container5nMqo29\srcPhabalicious_AppKernelProdContainer->load()
#3 phar:///usr/local/bin/phab/vendor/symfony/dependency-injection/Container.php(231): Symfony\Component\DependencyInjection\Container->make()
#4 phar:///usr/local/bin/phab/bin/phab(56): Symfony\Component\DependencyInjection\Container->get()
#5 /usr/local/bin/phab(14): require('phar:///usr/loc...')
#6 {main}
  thrown in phar:///usr/local/bin/phab/vendor/symfony/console/Application.php on line 489
```

**Comment by stmh** [comment]
strange, that the tests on the ci didnt catch this error. I had an outdated symfony cache on my local which made it work for me. 

should be fixed in beta.2
