### ISSUE TITLE
Allow passing env variables to docker-compose

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#254]
As a solution to xdebug giving errors for grumphp https://github.com/uselagoon/lagoon-images/pull/353#issuecomment-1057014150 I would want to disable xdebug when running pre-commit hooks.

This works with docker-compose like

```
docker-compose run -e XDEBUG_ENABLE= builder vendor/bin/grumphp git:pre-commit --skip-success-output
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/6: phplint... 
Running task 2/6: yamllint... 
Running task 3/6: composer... 
Running task 4/6: jsonlint... 
Running task 5/6: phpcs... 
Running task 6/6: npm_script...
```

But if I want to do same with phab it is not working, 

```
phab -cmbb docker-compose -- run -e XDEBUG_ENABLE= builder vendor/bin/grumphp git:pre-commit --skip-success-output
PHP Fatal error:  Uncaught InvalidArgumentException: The environment "XDEBUG_ENABLE=" contains invalid characters, it can only contain characters allowed in PHP class names. in phar:///usr/local/bin/phab/vendor/symfony/http-kernel/Kernel.php:478
Stack trace:
#0 phar:///usr/local/bin/phab/vendor/symfony/http-kernel/Kernel.php(504): Symfony\Component\HttpKernel\Kernel->getContainerClass()
#1 phar:///usr/local/bin/phab/vendor/symfony/http-kernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 phar:///usr/local/bin/phab/bin/phab(52): Symfony\Component\HttpKernel\Kernel->boot()
#3 /usr/local/bin/phab(14): require('...')
#4 {main}
  thrown in phar:///usr/local/bin/phab/vendor/symfony/http-kernel/Kernel.php on line 478
```

**Comment by stmh** [comment]
Culprit was an error in the handling of debug flags in `bin/phab`
