### ISSUE TITLE
Uncaught TypeError: Unsupported operand types: array + array

### ISSUE THREAD

**Issue by joachim-n** [factorial-io/phabalicious#272]
```
$ phab --version

Fatal error: Uncaught TypeError: Unsupported operand types: array + array in phar:///usr/local/bin/phab/vendor/symfony/console/Logger/ConsoleLogger.php:58
Stack trace:
#0 phar:///usr/local/bin/phab/src/Utilities/Logger.php(68): Symfony\Component\Console\Logger\ConsoleLogger->__construct(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array)
#1 /private/var/folders/zm/ym7sjy7s4hl54jr7yngljy4m0000gn/T/phabalicious3.7.107ea8cfa7b86c2865d3b638d690c7a809/ContainerH5IKkvY/getLoggerService.php(9): Phabalicious\Utilities\Logger->__construct(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /private/var/folders/zm/ym7sjy7s4hl54jr7yngljy4m0000gn/T/phabalicious3.7.107ea8cfa7b86c2865d3b638d690c7a809/ContainerH5IKkvY/srcPhabalicious_AppKernelProdContainer.php(64): require('/private/var/fo...')
#3 /private/var/folders/zm/ym7sjy7s4hl54jr7yngljy4m0000gn/T/phabalicious3.7.107ea8cfa7b86c2865d3b638d690c7a809/ContainerH5IKkvY/getConfigurationServiceService.php(15): ContainerH5IKkvY\srcPhabalicious_AppKernelProdContainer->load('getLoggerServic...')
#4 /private/var/folders/zm/ym7sjy7s4hl54jr7yngljy4m0000gn/T/phabalicious3.7.107ea8cfa7b86c2865d3b638d690c7a809/ContainerH5IKkvY/srcPhabalicious_AppKernelProdContainer.php(64): require('/private/var/fo...')
#5 /private/var/folders/zm/ym7sjy7s4hl54jr7yngljy4m0000gn/T/phabalicious3.7.107ea8cfa7b86c2865d3b638d690c7a809/ContainerH5IKkvY/getApplicationService.php(11): ContainerH5IKkvY\srcPhabalicious_AppKernelProdContainer->load('getConfiguratio...')
#6 /private/var/folders/zm/ym7sjy7s4hl54jr7yngljy4m0000gn/T/phabalicious3.7.107ea8cfa7b86c2865d3b638d690c7a809/ContainerH5IKkvY/srcPhabalicious_AppKernelProdContainer.php(64): require('/private/var/fo...')
#7 phar:///usr/local/bin/phab/vendor/symfony/dependency-injection/Container.php(255): ContainerH5IKkvY\srcPhabalicious_AppKernelProdContainer->load('getApplicationS...')
#8 phar:///usr/local/bin/phab/vendor/symfony/dependency-injection/Container.php(231): Symfony\Component\DependencyInjection\Container->make('Symfony\\Compone...', 1)
#9 phar:///usr/local/bin/phab/bin/phab(60): Symfony\Component\DependencyInjection\Container->get('Symfony\\Compone...')
#10 /usr/local/bin/phab(14): require('phar:///usr/loc...')
#11 {main}
  thrown in phar:///usr/local/bin/phab/vendor/symfony/console/Logger/ConsoleLogger.php on line 58
```

PHP is 8.0.8.

**Comment by joachim-n** [comment]
I've made a PR with a fix.

However, when I tried to isolate the problem, I can't reproduce it:

```
<?php

class ParentClass {

  private $verbosityLevelMap = [
    1
  ];

  public function __construct(array $verbosityLevelMap = []) {
    $this->verbosityLevelMap = $verbosityLevelMap + $this->verbosityLevelMap;
  }

}

class Child extends ParentClass {

  private $verbosityLevelMap = [
    2
  ];

  public function __construct() {
    parent::__construct($this->verbosityLevelMap);
  }

}

$c = new Child();
```

Weird!
